apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:hxV/V+pgMKFmb6j5JZr0oOokYAD6Z8jkO/7z/EHeCc64pXdQ,iv:m2MXC8yVTAR5vuDwLJaVBt1A3eThXy4GqdUHj8diVRI=,tag:4zxnwiIUPN2m2AyFJcSg5w==,type:str]
    credentials.json: ENC[AES256_GCM,data:2XD93lotKULhg2nl4wFL0NjRAhz18fatERw0r9wJMIWqf2WYGV+N8fef77TjistdXfJdCI9YIbCzz/VfkS5b330e4tGF+ckw/V93hoALfw4z5tiOMPsHlp2sXrOG+yNCSjSE/vuMzRgqCC0scl5JeBZD2Zp1liaRS0ZE+2zdfyNuXDAlatI09E5lcY6nqNGC0RhDQ5CIXaZoPeL4tjfKgGJBhvulJvw2hGb02hlAQQ==,iv:wJkfHUywEa+INKXMCkJ9758wCHPapF6hNVGfP9RMuvo=,tag:qAU+VpCx16flrHagCsrprQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1et3hqngns4egy9430vu63y6uwevtv5qmfxr6yy94qvf7pnxns4uq4en025
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVFprQ01wVTZ6Y09mM2lx
            Vk9ReGFCUzhtcVpjZnZ6ZTVYYjJ6bnI5NUdrCkl4U1BEd1JCb1IrMk1NalNydjRn
            TDZodjBIZ0NwYUdmNWZqL2tMbFlBZUkKLS0tIFoyNDhtc3MyNDhqcHBTL2JsajR6
            OEt0a0hkMTBucndYcDZ1K2N2QXc2UmcK4vfWltQ7hc73N6ZhzaX+JuauYFogPgY+
            fCOXyHGiIy+9T0iPgq+Zi6zRIMgIO70/sArUeLXefXIwtw86fcRLzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T01:17:33Z"
    mac: ENC[AES256_GCM,data:eSYeLtN4iBFWO4O92GSFa3R6lMbTyvqxn36HiBUPu0yaMcZs3ROGE1CKqSzDJGmmlPyMhe+3wclhvHD/TyExuRbp3LapNjBT2daMWc5Dmi0omRfRnMu7WIMC8im0MQFQ0GFxdiY/EoOyY7joR/105AExMf0/0ZjkWVA7c8oPX2Y=,iv:S7G5WI4SvRZeXZfTbLyyTPyUJUQBlj0wnfO2VT32Q3I=,tag:aPrEhAOJpgMXklSn2y3/9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
